### ISSUE TITLE
using website version results in error #1

### ISSUE THREAD

**Issue by tao840813** [sapiris/epitope_b_cells_predictor#2]
Dear CALIBER creators,
When I try to run BCE prediction on current version from GitHub with this command
`!python main.py --mode predict --init ESM-2 --model BiLSTM --epi Nonlinear --test_pdb_path ./test_pdb`

I got 
```Traceback (most recent call last):
  File "/content/epitope_b_cells_predictor/main.py", line 265, in <module>
    predict(params, save_dir)
  File "/content/epitope_b_cells_predictor/main.py", line 73, in predict
    test_data = load_data_pdb_path(params["pdb_id_path"], params)
  File "/content/epitope_b_cells_predictor/data_load.py", line 80, in load_data_pdb_path
    dict_chain_seq = extract_sequence_from_pdb(f"{path}/{filename}", pdb_id, params['pdb_dir'], params['distb_dir'])
KeyError: 'distb_dir'
```
I wondered if this is typo or not? (since I can not find the definition of  'distb_dir') or I just input command in wrong format?
Also, I can't access website version, I wonder if there is region restriction or just under maintain?

**Comment by tao840813** [comment]
I’m really sorry to trouble you with so many questions, but I have another issue that I’d like to clarify.

The create_batches function receives data, which is generated by the load_data_pdb_path function. However, load_data_pdb_path returns a tuple: (all_data, invalid_proteins). This causes the line for name_pro, protein, list_tag in data: in create_batches to fail because data only has two elements.
I tried to modify it to use data[0], the issue persists, in all_data, the list_tag (the third element of each tuple) is initialized as an empty list: all_data.append((chain, seq, [])). During my debugging process, I couldn't find any part of the code where this list_tag gets modified. As a result, length_pro becomes 0, which prevents the correct size of padded_peps from being generated to fix the input sequence length.

I feel like I may have misunderstood something, so I’d really appreciate your help in figuring this out. Again, I’m sorry for asking so many questions and taking up your time.

**Comment by sapiris** [comment]
I apologize for the trouble with running the code. I’ve updated the git, so it should work now. 
The website is intended to work for everyone, but there is a technical issue. We’re working on fixing it, and I’ll update you as soon as it’s resolved. 
Please let us know if you encounter any further issues.

**Comment by tao840813** [comment]
Dear CALIBER Team,

Thank you for modifying the code! In my case, I also needed to further modify line 88 in models.py from:
device = params["device"] -> device = torch.device('cuda')
to make it work properly.

I’m also looking forward to the day your website is fully functional. Wishing you all the best!

**Comment by tao840813** [comment]
Dear CALIBER Team,

I would like to inquire about the default threshold value used in Caliber.

Sorry—I understand that the last column in the CSV already provides 1/0 labels, and from Figure 2 in the original paper, the threshold appears to be around 0.2. However, I would still like to confirm the exact value.

Thank you!

**Comment by sapiris** [comment]
Hello

The threshold value depends on the combination of the parameters you choose for the model (e.g., BiLSTM, GCN), the encoding method (e.g., ESM-2), and the epitope type (e.g., linear or conformational). You can find the exact values for each combination in main.py, lines 158–170.

**Comment by tao840813** [comment]
Dear CALIBER Team,

Thank you! Really appreciate for help!
